version: "2.1"
services:
  discord_bot:
    platform: linux/amd64
    container_name: discord_bot
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./app-variables.env
    volumes:
      - ./app:/app_home/app
